name: Build and push docker images
on:
  push:
    branches: 
      - '**' # Every branch

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - run: docker-compose build
    - run: docker tag compiler mruntime/compiler
    - run: docker push mruntime/compiler
    - run: docker tag executor mruntime/executor
    - run: docker push mruntime/executor
    - run: docker tag orchestrator mruntime/orchestrator
    - run: docker push mruntime/orchestrator
    - run: docker tag orm mruntime/orm
    - run: docker push mruntime/orm
    - run: docker tag verdict mruntime/verdict
    - run: docker push mruntime/verdict 